version: "3"

services:
  #MongoDB
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - 5000:4000
    environment:
      APP_NAME: LedgerApp
      PORT: 4000
      DB_URI: mongodb://mongo_db:27017/ledger_app
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}